### ISSUE TITLE
Require farady_middleware in new install

### ISSUE THREAD

**Issue by BoGs** [atomita/fluent-plugin-aws-elasticsearch-service#1]
Trying to install in docker image and getting

```
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- faraday_middleware (LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-aws-elasticsearch-service-0.0.3/lib/fluent/plugin/out_aws-elasticsearch-service.rb:6:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin.rb:148:in `block in try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin.rb:146:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin.rb:146:in `try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin.rb:106:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin.rb:57:in `new_output'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:41:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:34:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:34:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:127:in `add_match'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:60:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:54:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:54:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:82:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:93:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:77:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:457:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:141:in `block in start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `call'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `main_process'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:281:in `block in supervise'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `fork'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `supervise'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:137:in `start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/bin/fluentd:6:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
```

I was using the general install command for fluentd

```
td-agent-gem install fluent-plugin-aws-elasticsearch-service
```

thoughts?

**Comment by tyronedougherty** [comment]
I've got the same issue here. Any suggestions from people? It seems like [previously](https://github.com/lostisland/faraday_middleware/issues/82) Faraday Middleware was not compatible with Faraday 0.9 but that looks like it was [fixed ?](https://github.com/lostisland/faraday_middleware/releases/tag/v0.9.1)

I'm not a ruby dev so I'm not particularly familiar with where to go from here, so any suggestions would be helpful! :)

**Comment by tyronedougherty** [comment]
I've found the source of the issue and have a fix! It seems that Ruby was not installing the gems in a place that the td-agent user has access to and therefore could not require the faraday_middleware gem. To fix this, first uninstall faraday_middle ware with
```
sudo gem uninstall faraday_middleware
```
then reinstall it under the td-agent user using the following command:
```
sudo -u td-agent /usr/sbin/td-agent-gem install faraday_middleware
```

I also then stumbled across an issue whereby the plugin was unable to connect to our AWS Elasticsearch endpoint when we were just specifying the domain. To fix this, you must specify the protocol and port. For example, our endpoint config now looks like this:
```
<endpoint>
   url "http://xxx.ap-southeast-2.es.amazonaws.com:80"
   region "ap-southeast-2"
   access_key_id "xxx"
   secret_access_key "xxx"
</endpoint>
```

I hope this fixes any issues anyone might have!
cc @BoGs

**Comment by atomita** [comment]
Hi BoGs.

I'm sorry, "v0.0. *" is bug-ridden.
Please try using the "v0.1.0".

thanks!

**Comment by atomita** [comment]
sorry...

I was mistaken dependencies.
I removed the "require 'faraday_middleware'".

Please try using the "v0.1.1".

thanks

**Comment by fragtom** [comment]
thx..

**Comment by fragtom** [comment]
thx for fixing that lines, I've removed gem install procedure of my docker container.

**Comment by BoGs** [comment]
Thanks for the new version - it is working now. Thanks for the quick response.

**Comment by atomita** [comment]
Thank you for the reply!
