### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by dieend** [atomita/fluent-plugin-aws-elasticsearch-service#5]
```
2015-11-16 14:56:55 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-16 14:57:05 +0000 error_class="NoMethodError" error="undefined method `credentials' for nil:NilClass" plugin_id="object:3fc87c3ce914"
```
I installed this plugin using `/opt/td-agent/embedded/fluent-gem install fluent-plugin-aws-elasticsearch-service`

**Comment by KasparBP** [comment]
I am getting the same error

**Comment by gpaszkowski-rmn** [comment]
Same here.  Started with the official fluent/fluentd docker image and then did:
 `fluent-gem install fluent-plugin-aws-elasticsearch-service`

My config is:
```
<match **>
  type aws-elasticsearch-service
  type_name "testing"
  <endpoint>
    url "<my cluster url here>"
    region "us-west-1"
    access_key_id "<my key id here>"
    secret_access_key "<my secret key here>"
  </endpoint>
  include_tag_key true
  logstash_format true
  request_timeout 120s
  retry_limit 300
  retry_wait 5s
  tag_key tag
</match>
```

The Error:
```
2015-11-17 22:40:42 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-17 22:40:47 +0000 error_class="NoMethodError" error="undefined method `credentials' for nil:NilClass" plugin_id="object:3fa78dfcdb58"
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/signers/v4.rb:24:in `initialize'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday_middleware-aws-signers-v4-0.1.5/lib/faraday_middleware/request/aws_signers_v4.rb:56:in `new'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday_middleware-aws-signers-v4-0.1.5/lib/faraday_middleware/request/aws_signers_v4.rb:56:in `call'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `call'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `perform_request'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:20:in `block in ping'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.1.0/lib/fluent/plugin/out_elasticsearch.rb:69:in `client'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.1.0/lib/fluent/plugin/out_elasticsearch.rb:176:in `rescue in send'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.1.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `send'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.1.0/lib/fluent/plugin/out_elasticsearch.rb:168:in `write'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.16/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.16/lib/fluent/buffer.rb:304:in `pop'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.16/lib/fluent/output.rb:321:in `try_flush'
  2015-11-17 22:40:42 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.16/lib/fluent/output.rb:140:in `run'
```

**Comment by aj-jester** [comment]
I downgraded back to `0.1.2` and that seems to work

**Comment by atomita** [comment]
Sorry, Depending on the version up of faraday_middleware-aws-signers-v4 it seems error has occurred.

I'll use the version 0.1.1 for now.

**Comment by gpaszkowski-rmn** [comment]
This worked for me.  Thanks!

**Comment by aj-jester** [comment]
Confirmed the latest version (0.1.4) works. Thanks @atomita for fixing.

**Comment by atomita** [comment]
Thank you for the report!
