### ISSUE TITLE
Getting "ArgumentError" on docker

### ISSUE THREAD

**Issue by pussade** [atomita/fluent-plugin-aws-elasticsearch-service#52]
Hello.

I'm trying post to an ES 6.4 domain in AWS using the fluentd container on docker but getting the following error.
What is the wrong?

```
docker-fluentd |   <source>
docker-fluentd |     @type forward
docker-fluentd |     port 24224
docker-fluentd |     bind "0.0.0.0"
docker-fluentd |   </source>
docker-fluentd |   <match docker.docker-nginx.**>
docker-fluentd |     @type aws-elasticsearch-service
docker-fluentd |     type_name "access_log"
docker-fluentd |     logstash_format true
docker-fluentd |     include_tag_key true
docker-fluentd |     tag_key "@log_name"
docker-fluentd |     flush_interval 1s
docker-fluentd |     <endpoint>
docker-fluentd |       url "https://search-**************************.ap-northeast-1.es.amazonaws.com"
docker-fluentd |       region "ap-northeast-1"
docker-fluentd |     </endpoint>
docker-fluentd |     <buffer>
docker-fluentd |       flush_interval 1s
docker-fluentd |     </buffer>
docker-fluentd |   </match>
docker-fluentd | </ROOT>
docker-fluentd | 2019-03-03 14:51:14 +0000 [info]: starting fluentd-1.3.3 pid=6 ruby="2.5.2"
docker-fluentd | 2019-03-03 14:51:14 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
docker-fluentd | 2019-03-03 14:51:15 +0000 [info]: gem 'fluent-plugin-aws-elasticsearch-service' version '2.0.0'
docker-fluentd | 2019-03-03 14:51:15 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.3.0'
docker-fluentd | 2019-03-03 14:51:15 +0000 [info]: gem 'fluentd' version '1.3.3'
docker-fluentd | 2019-03-03 14:51:15 +0000 [info]: adding match pattern="docker.docker2-nginx.**" type="aws-elasticsearch-service"
docker-fluentd | 2019-03-03 14:51:16 +0000 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
docker-fluentd | 2019-03-03 14:51:16 +0000 [error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (given 1, expected 0)"
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-aws-elasticsearch-service-2.0.0/lib/fluent/plugin/out_aws-elasticsearch-service.rb:34:in `get_connection_options'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.3.0/lib/fluent/plugin/out_elasticsearch.rb:353:in `client'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.3.0/lib/fluent/plugin/elasticsearch_index_template.rb:36:in `rescue in retry_operate'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.3.0/lib/fluent/plugin/elasticsearch_index_template.rb:34:in `retry_operate'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.3.0/lib/fluent/plugin/out_elasticsearch.rb:238:in `configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin.rb:164:in `configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/agent.rb:130:in `add_match'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/agent.rb:72:in `block in configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/agent.rb:64:in `each'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/agent.rb:64:in `configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/root_agent.rb:112:in `configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:131:in `configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/engine.rb:96:in `run_configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:795:in `run_configure'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:548:in `block in run_worker'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:724:in `main_process'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/supervisor.rb:544:in `run_worker'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/bin/fluentd:8:in `<top (required)>'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
docker-fluentd |   2019-03-03 14:51:16 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
docker-fluentd | 2019-03-03 14:51:16 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

Incidentally the following is my Dockerfile about fluentd image.
```
FROM fluent/fluentd:v1.3.3-onbuild-1.0

# Use root account to use apk
USER root

# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev
RUN sudo gem install \
        fluent-plugin-elasticsearch \
        fluent-plugin-aws-elasticsearch-service \
    && sudo gem sources --clear-all \
    && apk del .build-deps \
    && rm -rf /home/fluent/.gem/ruby/2.5.0/cache/*.gem

USER fluent
```

**Comment by cosmo0920** [comment]
This is caused by `get_connection_options` arity and usage change.
Could you try v2.1.0?

**Comment by pussade** [comment]
I tried v2.1.0 and succeed to post!
Thanks your swift response!
