### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by jdrydn** [atomita/fluent-plugin-aws-elasticsearch-service#7]
Hi there,

I'm trying to setup this plugin in place of the standard `fluent-plugin-elasticsearch` for our AWS ES instance, and trying to drop-in-replace this plugin always fails with the error "`no implicit conversion of nil into String`". I'm having trouble trying to debug it and I was wondering if you could spot anything obvious that I'm doing wrong?

Below are extracts of our `td-agent.log`:

```
2016-03-01 10:57:57 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-03-01 10:57:57 +0000 [info]: starting fluentd-0.12.12
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-aws-elasticsearch-service' version '0.1.4'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-bufferize' version '0.0.1'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.0.0'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.10'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.4.1'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-s3' version '0.5.9'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.3.2'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-slack' version '0.6.2'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-td' version '0.10.27'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.1'
2016-03-01 10:57:57 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-03-01 10:57:57 +0000 [info]: gem 'fluentd' version '0.12.12'
2016-03-01 10:57:57 +0000 [info]: gem 'fluentd' version '0.10.61'
2016-03-01 10:57:57 +0000 [info]: using configuration file: <ROOT>
...
  # Application logs should go to ElasticSearch
  <match app.**>
  # @type elasticsearch
  # host search-xxxxxxxx.us-east-1.es.amazonaws.com
  # port 443
  # scheme https
  # include_tag_key true
  # tag_key @log_name
  # logstash_format true
  # flush_interval 5s
  # buffer_type file
  # buffer_path /etc/td-agent/buffer-es/
  # buffer_chunk_limit 5m
  # buffer_queue_limit 1024

    @type aws-elasticsearch-service
    include_tag_key true
    tag_key "@log_name"
    flush_interval 5s

    buffer_type file
    buffer_path /etc/td-agent/buffer-es/
    buffer_chunk_limit 5m
    buffer_queue_limit 1024

    <endpoint>
      url https://search-xxxxxxxx.us-east-1.es.amazonaws.com
      region us-east-1
    </endpoint>
  </match>
</ROOT>
2016-03-01 10:57:58 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2016-03-01 10:58:28 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-01 10:57:59 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:3feea97bc960"
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.20/lib/aws-sdk-core/signers/v4.rb:116:in `+'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.20/lib/aws-sdk-core/signers/v4.rb:116:in `signature'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.20/lib/aws-sdk-core/signers/v4.rb:106:in `authorization'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.20/lib/aws-sdk-core/signers/v4.rb:58:in `sign'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-aws-elasticsearch-service-0.1.4/lib/fluent/plugin/out_aws-elasticsearch-service.rb:163:in `sign'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday_middleware-aws-signers-v4-0.1.1/lib/faraday_middleware/request/aws_signers_v4.rb:40:in `call'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/base.rb:191:in `call'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/base.rb:191:in `perform_request'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:119:in `perform_request'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/actions/ping.rb:20:in `block in ping'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:64:in `client'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:171:in `rescue in send'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:169:in `send'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:163:in `write'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2016-03-01 10:58:28 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
```

I believed since this plugin (appears to) extend the ES plugin (with a few additional IAM features) it would be simple enough to replace, but I can't work out why this error is being thrown :cry:

**Comment by jdrydn** [comment]
And the only record of this error I can find here is [on this comment](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/2#issuecomment-154919481) and then @mzahidriaz reports he was successful with this plugin, so I think I'm close!

@mzahidriaz Is there any chance you could share (roughly) your config (either here or in #2) so we can understand the differences?

**Comment by mzahidriaz** [comment]
@jdrydn I'd love to share my config. But unfortunately I won't have those configuration with me. I started out to use this plugin to push the fluent logs directly to amazon elasticsearch service, but then we decided to use our own backup instance to store logs and push month old logs to S3.

Try adding credentials to your fluent setting.

**Comment by mzahidriaz** [comment]
Also for standard policy to AWS elasticsearch service

Created a new group and add your user to that group, then set the policy for the elasticsearch service and allow the access to your IAM group.

In this way any user to that group can push the data to elasticsearch service.

And then use your aws access key and secret in configuration

**Comment by jdrydn** [comment]
@mzahidriaz Thanks for getting back to me :+1: I'll definitely setup a new IAM user for this ES instance and try from there. Also fantastic advice with the policy & groups. I'm definitely going to do that today!

Does that mean this plugin **will always fail** whenever the access key and/or secret is omitted? At the moment I'm using the internal IPs for authentication (since the original ES plugin doesn't support IAM credentials) and I thought I could just switch to this plugin without any config changes before switching to an IAM user - guess I was wrong! :stuck_out_tongue_winking_eye:

**Comment by cosmo0920** [comment]
#12 should clarify this opaque error. Closing.
