### ISSUE TITLE
unable to sign request without credentials set when role-arn is provided to plugin

### ISSUE THREAD

**Issue by gpodila-disc** [atomita/fluent-plugin-aws-elasticsearch-service#71]
#### Problem
unable to sign request without credentials set with role-arn, I tried with right role arn but working fine with access_key_id and secret_access_key which is working fine.

Im trying to send logs from k8s to aws elastic search and I see fluentd logs with  error_class=Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set"
...

#### Steps to replicate
I used the example https://github.com/aws-samples/amazon-eks-fluent-logging-examples/tree/mainline/examples/aggregator-to-amazon-elasticsearch to create filebeat, fluentd and publish logs to elastic search.

I create env variables with AWS creds and yet I see the above error in fluentd logs.
```
            - name: AWS_IAM_ROLE_ARN
              value: "arn:aws:iam::***:role/test-role"
```

```
          url "#{ENV['AWS_ES_URL']}"
          region "#{ENV['AWS_ES_REGION']}"
          assume_role_arn "#{ENV['AWS_IAM_ROLE_ARN']}"
````

```
2021-07-17 16:00:18 +0000 [error]: #0 unexpected error error_class=Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set"
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/signature_v4.rb:72:in `sign_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/signature_v4.rb:112:in `apply_signature'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/signature_v4.rb:65:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/retry_errors.rb:177:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/query/handler.rb:28:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/seahorse/client/request.rb:70:in `send_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-sts/client.rb:603:in `assume_role'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-aws-elasticsearch-service-2.2.0/lib/fluent/plugin/out_aws-elasticsearch-service.rb:115:in `new'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-aws-elasticsearch-service-2.2.0/lib/fluent/plugin/out_aws-elasticsearch-service.rb:115:in `sts_credential_provider'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-aws-elasticsearch-service-2.2.0/lib/fluent/plugin/out_aws-elasticsearch-service.rb:89:in `block in credentials'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-aws-elasticsearch-service-2.2.0/lib/fluent/plugin/out_aws-elasticsearch-service.rb:107:in `inspect'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:58:in `inspect'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:58:in `redact'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:52:in `block in redacted_string'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:51:in `each'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:51:in `reduce'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:51:in `redacted_string'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/redacted.rb:36:in `inspect'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:311:in `rescue in perform_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:258:in `perform_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-api-7.3.0/lib/elasticsearch/api/actions/info.rb:19:in `info'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.5.6/lib/fluent/plugin/out_elasticsearch.rb:341:in `detect_es_major_version'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.5.6/lib/fluent/plugin/out_elasticsearch.rb:248:in `block in configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.5.6/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.5.6/lib/fluent/plugin/out_elasticsearch.rb:247:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/plugin.rb:164:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:130:in `add_match'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:72:in `block in configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `each'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/label.rb:31:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `block in configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `each'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:131:in `configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/engine.rb:96:in `run_configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:812:in `run_configure'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:558:in `block in run_worker'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:741:in `main_process'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:554:in `run_worker'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.7.4/bin/fluentd:8:in `<top (required)>'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2021-07-17 16:00:18 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
2021-07-17 16:00:18 +0000 [info]: Worker 0 finished unexpectedly with status 1
2021-07-17 16:00:18 +0000 [info]: gem 'fluent-plugin-aws-elasticsearch-service' version '2.2.0'
2021-07-17 16:00:18 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.6'
2021-07-17 16:00:18 +0000 [info]: gem 'fluentd' version '1.7.4'
2021-07-17 16:00:18 +0000 [info]: adding match in @ES pattern="kube.var.log.containers.fluent**" type="null"
2021-07-17 16:00:18 +0000 [info]: adding filter in @ES pattern="kube.var.log.containers.apache**" type="parser"
2021-07-17 16:00:18 +0000 [info]: adding match in @ES pattern="**" type="aws-elasticsearch-service"
```

```
#### Expected Behavior or What you need to ask
Logs written to AWS elastic search
...

**Comment by gpodila-disc** [comment]
wrong k8 config, add `hostNetwork: true` in template spec. Which fixed the issue.

**Comment by cafuego** [comment]
A bit late to the party, but this cna be fixed without changing the container network mode by allowing more than 1 network hop to reach the metadata service: https://stackoverflow.com/questions/71884350/using-imds-v2-with-token-inside-docker-on-ec2-or-ecs/71884476#71884476
