### ISSUE TITLE
Fluentd Pod giving error "C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:144:in `include': wrong argument type Class (expected Module) (TypeError)"

### ISSUE THREAD

**Issue by AnilKumarChauhan2021** [atomita/fluent-plugin-aws-elasticsearch-service#85]
#### Problem
C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:144:in `include': wrong argument type Class (expected Module) (TypeError)
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:144:in `<module:Client>'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:143:in `<module:Elasticsearch>'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:141:in `<class:ElasticsearchOutput>'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:140:in `<module:Plugin>'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluent-plugin-aws-elasticsearch-service-2.4.1/lib/fluent/plugin/out_aws-elasticsearch-service.rb:9:in `<top (required)>'
	from <internal:C:/ruby31/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/ruby31/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/registry.rb:103:in `block in search'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/registry.rb:100:in `each'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/registry.rb:100:in `search'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/registry.rb:44:in `lookup'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/plugin.rb:169:in `new_impl'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/plugin.rb:114:in `new_output'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/agent.rb:130:in `add_match'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/agent.rb:74:in `block in configure'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/agent.rb:64:in `each'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/agent.rb:64:in `configure'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/root_agent.rb:149:in `configure'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/engine.rb:105:in `configure'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/engine.rb:80:in `run_configure'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/supervisor.rb:731:in `run_supervisor'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
	from <internal:C:/ruby31/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/ruby31/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from C:/ruby31/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3-x64-mingw-ucrt/bin/fluentd:15:in `<top (required)>'
	from C:/ruby31/bin/fluentd:32:in `load'
	from C:/ruby31/bin/fluentd:32:in `<main>'
...

#### Steps to replicate
We are upgrading our eks cluster from 1.24 to 1.25, we have both windows and linux nodes in our cluster. Fluentd is working fine on linux nodes, but we started seeing this error on **windows** nodes. For windows node we build custom image using below docker file

`FROM mcr.microsoft.com/windows/servercore:ltsc2022
LABEL maintainer "Fluentd developers <fluentd@googlegroups.com>"
LABEL Description="Fluentd docker image" Vendor="Fluent Organization" Version="1.15.3"
RUN powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
RUN choco install -y ruby --version 3.1.2.1 --params "'/InstallDir:C:\ruby31'" \&& choco install -y msys2 --version 20220904.0.0 --params "'/NoPath /NoUpdate /InstallDir:C:\ruby31\msys64'"
RUN refreshenv \
&& ridk install 3 \
&& echo gem: --no-document >> C:\ProgramData\gemrc \
&& gem install oj -v 3.13.22 \
&& gem install json -v 2.6.2 \
&& gem install rexml -v 3.2.5 \
&& gem install fluentd -v 1.15.3 \
&& gem install win32-service -v 2.3.2 \
&& gem install win32-ipc -v 0.7.0 \
&& gem install win32-event -v 0.6.3 \
&& gem install elasticsearch -v 7.14.1 \
&& gem install fluent-plugin-elasticsearch \
&& gem install fluent-plugin-aws-elasticsearch-service \
&& gem install fluent-plugin-detect-exceptions \
&& gem install fluent-plugin-kubernetes_metadata_filter \
&& gem install fluent-plugin-multi-format-parser \
&& gem install fluent-plugin-parser-cri --no-document \ 
&& gem install fluent-plugin-systemd \
&& gem install fluent-plugin-grok-parser \
&& gem install fluent-plugin-prometheus \
&& gem install fluent-plugin-concat \
&& gem install fluent-plugin-dedot_filter \
&& gem sources --clear-all`

Provide example config and message
below is the image build pipeline output
`2023-07-19T05:34:35.2938918Z Temporarily enhancing PATH for MSYS/MINGW...
2023-07-19T05:34:35.2941445Z Building native extensions. This could take a while...
2023-07-19T05:34:35.2942508Z Successfully installed oj-3.13.22
2023-07-19T05:34:35.2943282Z 1 gem installed
2023-07-19T05:34:51.0562968Z Temporarily enhancing PATH for MSYS/MINGW...
2023-07-19T05:34:51.0568824Z Building native extensions. This could take a while...
2023-07-19T05:34:51.0570435Z Successfully installed json-2.6.2
2023-07-19T05:34:51.0571121Z 1 gem installed
2023-07-19T05:34:52.6716499Z Successfully installed rexml-3.2.5
2023-07-19T05:34:52.6718254Z 1 gem installed
2023-07-19T05:37:15.3691902Z Temporarily enhancing PATH for MSYS/MINGW...
2023-07-19T05:37:15.3701026Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3703439Z Successfully installed yajl-ruby-1.4.3
2023-07-19T05:37:15.3704438Z Successfully installed ffi-1.15.5-x64-mingw-ucrt
2023-07-19T05:37:15.3705126Z Successfully installed ffi-win32-extensions-1.0.4
2023-07-19T05:37:15.3705701Z Successfully installed win32-service-2.3.2
2023-07-19T05:37:15.3706216Z Successfully installed win32-ipc-0.7.0
2023-07-19T05:37:15.3706860Z Successfully installed win32-event-0.6.3
2023-07-19T05:37:15.3707471Z Successfully installed webrick-1.7.0
2023-07-19T05:37:15.3708184Z Successfully installed concurrent-ruby-1.2.2
2023-07-19T05:37:15.3708795Z Successfully installed tzinfo-2.0.6
2023-07-19T05:37:15.3709475Z Successfully installed tzinfo-data-1.2023.3
2023-07-19T05:37:15.3710760Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3711431Z Successfully installed strptime-0.2.5
2023-07-19T05:37:15.3712518Z Successfully installed sigdump-0.2.5
2023-07-19T05:37:15.3713837Z Successfully installed serverengine-2.3.2
2023-07-19T05:37:15.3715915Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3716913Z Successfully installed msgpack-1.7.2
2023-07-19T05:37:15.3718913Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3719621Z Successfully installed http_parser.rb-0.8.0
2023-07-19T05:37:15.3720186Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3720810Z Successfully installed cool.io-1.7.1
2023-07-19T05:37:15.3721355Z Building native extensions. This could take a while...
2023-07-19T05:37:15.3722271Z Successfully installed certstore_c-0.1.7
2023-07-19T05:37:15.3722944Z Successfully installed fluentd-1.15.3-x64-mingw-ucrt
2023-07-19T05:37:15.3723469Z 18 gems installed
2023-07-19T05:37:17.2546819Z Successfully installed win32-service-2.3.2
2023-07-19T05:37:17.2548836Z 1 gem installed
2023-07-19T05:37:18.8062126Z Successfully installed win32-ipc-0.7.0
2023-07-19T05:37:18.8063883Z 1 gem installed
2023-07-19T05:37:20.4579039Z Successfully installed win32-event-0.6.3
2023-07-19T05:37:20.4580950Z 1 gem installed
2023-07-19T05:37:27.6105729Z Successfully installed multi_json-1.15.0
2023-07-19T05:37:27.6107402Z Successfully installed faraday-retry-1.0.3
2023-07-19T05:37:27.6108589Z Successfully installed faraday-rack-1.0.0
2023-07-19T05:37:27.6109272Z Successfully installed faraday-patron-1.0.0
2023-07-19T05:37:27.6109930Z Successfully installed faraday-net_http_persistent-1.2.0
2023-07-19T05:37:27.6110573Z Successfully installed faraday-net_http-1.0.1
2023-07-19T05:37:27.6111195Z Successfully installed multipart-post-2.3.0
2023-07-19T05:37:27.6111836Z Successfully installed faraday-multipart-1.0.4
2023-07-19T05:37:27.6112461Z Successfully installed faraday-httpclient-1.0.1
2023-07-19T05:37:27.6113091Z Successfully installed faraday-excon-1.1.0
2023-07-19T05:37:27.6114635Z Successfully installed faraday-em_synchrony-1.0.0
2023-07-19T05:37:27.6115342Z Successfully installed faraday-em_http-1.0.0
2023-07-19T05:37:27.6115975Z Successfully installed faraday-1.10.3
2023-07-19T05:37:27.6116611Z Successfully installed elasticsearch-transport-7.14.1
2023-07-19T05:37:27.6117248Z Successfully installed elasticsearch-api-7.14.1
2023-07-19T05:37:27.6117868Z Successfully installed elasticsearch-7.14.1
2023-07-19T05:37:27.6118388Z 16 gems installed
2023-07-19T05:37:36.9280962Z Successfully installed faraday-net_http-3.0.2
2023-07-19T05:37:36.9282455Z Successfully installed faraday-2.7.10
2023-07-19T05:37:36.9283209Z Successfully installed excon-0.100.0
2023-07-19T05:37:36.9283869Z Successfully installed faraday-excon-2.1.0
2023-07-19T05:37:36.9284508Z Successfully installed elastic-transport-8.2.2
2023-07-19T05:37:36.9285275Z Successfully installed elasticsearch-api-8.8.0
2023-07-19T05:37:36.9285982Z Successfully installed elasticsearch-8.8.0
2023-07-19T05:37:36.9286632Z Successfully installed fluent-plugin-elasticsearch-5.3.0
2023-07-19T05:37:36.9287163Z 8 gems installed
2023-07-19T05:37:46.0141007Z Successfully installed aws-eventstream-1.2.0
2023-07-19T05:37:46.0142986Z Successfully installed aws-sigv4-1.6.0
2023-07-19T05:37:46.0143803Z Successfully installed faraday_middleware-aws-sigv4-0.3.0
2023-07-19T05:37:46.0144481Z Successfully installed jmespath-1.6.2
2023-07-19T05:37:46.0145078Z Successfully installed aws-partitions-1.788.0
2023-07-19T05:37:46.0145771Z Successfully installed aws-sdk-core-3.178.0
2023-07-19T05:37:46.0146441Z Successfully installed fluent-plugin-aws-elasticsearch-service-2.4.1
2023-07-19T05:37:46.0146985Z 7 gems installed
2023-07-19T05:37:50.9747972Z Successfully installed fluent-plugin-detect-exceptions-0.0.15
2023-07-19T05:37:50.9749820Z 1 gem installed
2023-07-19T05:38:05.6711442Z Successfully installed lru_redux-1.1.0
2023-07-19T05:38:05.6713692Z Successfully installed netrc-0.11.0
2023-07-19T05:38:05.6714372Z Successfully installed mime-types-data-3.2023.0218.1
2023-07-19T05:38:05.6714958Z Successfully installed mime-types-3.4.1
2023-07-19T05:38:05.6715546Z Successfully installed unf_ext-0.0.8.2-x64-mingw-ucrt
2023-07-19T05:38:05.6716115Z Successfully installed unf-0.1.4
2023-07-19T05:38:05.6716695Z Successfully installed domain_name-0.5.20190701
2023-07-19T05:38:05.6717263Z Successfully installed http-cookie-1.0.5
2023-07-19T05:38:05.6717774Z Successfully installed http-accept-1.7.0
2023-07-19T05:38:05.6718460Z Successfully installed rest-client-2.1.0
2023-07-19T05:38:05.6719149Z Successfully installed recursive-open-struct-1.1.3
2023-07-19T05:38:05.6719722Z Successfully installed jsonpath-1.1.3
2023-07-19T05:38:05.6720275Z Successfully installed ffi-compiler-1.0.1
2023-07-19T05:38:05.6720772Z Temporarily enhancing PATH for MSYS/MINGW...
2023-07-19T05:38:05.6721262Z Building native extensions. This could take a while...
2023-07-19T05:38:05.6721906Z Successfully installed llhttp-ffi-0.4.0
2023-07-19T05:38:05.6722417Z Successfully installed http-form_data-2.3.0
2023-07-19T05:38:05.6722980Z Successfully installed public_suffix-5.0.3
2023-07-19T05:38:05.6723544Z Successfully installed addressable-2.8.4
2023-07-19T05:38:05.6724085Z Successfully installed http-5.1.1
2023-07-19T05:38:05.6725664Z Successfully installed kubeclient-4.11.0
2023-07-19T05:38:05.6726300Z Successfully installed fluent-plugin-kubernetes_metadata_filter-3.2.0
2023-07-19T05:38:05.6726968Z 20 gems installed
2023-07-19T05:38:10.2643793Z Successfully installed fluent-plugin-multi-format-parser-1.0.0
2023-07-19T05:38:10.2645426Z 1 gem installed
2023-07-19T05:38:14.8495938Z Successfully installed fluent-plugin-parser-cri-0.1.1
2023-07-19T05:38:14.8501589Z 1 gem installed
2023-07-19T05:38:19.5048584Z Successfully installed systemd-journal-1.4.2
2023-07-19T05:38:19.5050485Z Successfully installed fluent-plugin-systemd-1.0.5
2023-07-19T05:38:19.5051463Z 2 gems installed
2023-07-19T05:38:23.6484578Z Successfully installed fluent-plugin-grok-parser-2.6.2
2023-07-19T05:38:23.6485996Z 1 gem installed
2023-07-19T05:38:28.5997797Z Successfully installed prometheus-client-4.1.0
2023-07-19T05:38:28.5999464Z Successfully installed fluent-plugin-prometheus-2.1.0
2023-07-19T05:38:28.6000143Z 2 gems installed
2023-07-19T05:38:33.2457499Z Successfully installed fluent-plugin-concat-2.5.0
2023-07-19T05:38:33.2459410Z 1 gem installed
2023-07-19T05:38:37.3813372Z Successfully installed fluent-plugin-dedot_filter-1.0.0`
#### Expected Behavior or What you need to ask
Fluentd should start. Any help would be appreciated.

**Comment by AnilKumarChauhan2021** [comment]
Found the solution, pls refer to this
[https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/74](url)

Finally we changed the `fluent-plugin-aws-elasticsearch-service` to` fluent-plugin-opensearch` in dokcer file. 
also we updated the fluentd config to @type "opensearch"
